ENVIRONMENT: "dev"

DB_NAME: "d3uvq5hscmp9s4"
DB_HOST: "ec2-79-125-12-48.eu-west-1.compute.amazonaws.com"
DB_USER: "cmjqmvaxbayxcb"
DB_PASSWORD: "a21ca674a8aea319b21491f1fe294e45fc3ffafc5620b78c3f07bbfc9d7d2716"
DB_PORT: "5432"

APP_PORT: "5000"
APP_NAME: "todo-app"
APP_VERSION: "0.0.1"